<?php

$CONF_WEBISSUES_OPENVAS_LOGIN = "openvas";
$CONF_WEBISSUES_OPENVAS_PASSWORD = "openvas";
$CONF_WEBISSUES_WS_ENDPOINT = "http://localhost:8080/webissues-server-1.1.4/client/webservices.php";
$CONF_WEBISSUES_FOLDER_SCANS = 88;
$CONF_WEBISSUES_FOLDER_SERVERS = 86;
$CONF_WEBISSUES_IP_SEPARATOR = ',';
$CONF_FILE_IP_SEPARATOR = '|';

?>