<?php

$CONF_OPENVAS_WS_LOGIN = "test";
$CONF_OPENVAS_WS_PASSWORD = "test";
$CONF_OPENVAS_WS_ENDPOINT = "http://localhost:8080/webissues-server-1.1.4/client/security_tools/openvas/openvas.php";
$CONF_ID_ATTRIBUTE_FOLDER_CODES_PATH = 276;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_USE = 275;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_IPSADDRESS = 274;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TOOL = 277;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TIME = 278;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_SEVERITY = 279;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TARGETID = 280;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TASKID = 281;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_REPORTID = 282;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_ALERTID = 283;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_TARGET = 273;
$CONF_ID_TYPE_FOLDER_BUGS = 2;
$CONF_ID_TYPE_FOLDER_SERVERS = 147;
$CONF_ID_TYPE_FOLDER_CODES = 148;
$CONF_ID_TYPE_FOLDER_SCANS = 149;

?>