<?php

$CONF_OPENVAS_WS_LOGIN = "test";
$CONF_OPENVAS_WS_PASSWORD = "test";
$CONF_OPENVAS_WS_ENDPOINT = "http://localhost:8080/webissues-server-1.1.4/client/security_tools/openvas/openvas.php";
$CONF_ID_ATTRIBUTE_FOLDER_WEB_URL = 324;
$CONF_ID_ATTRIBUTE_FOLDER_CODES_PATH = 323;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_USE = 322;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_IPSADDRESS = 321;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TOOL = 325;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TIME = 326;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_SEVERITY = 327;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TARGETID = 328;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TASKID = 329;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_REPORTID = 330;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_ALERTID = 331;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_TARGET = 320;
$CONF_ID_TYPE_FOLDER_BUGS = 2;
$CONF_ID_TYPE_FOLDER_SERVERS = 170;
$CONF_ID_TYPE_FOLDER_CODES = 171;
$CONF_ID_TYPE_FOLDER_WEB = 173;
$CONF_ID_TYPE_FOLDER_SCANS = 172;

?>