<?php

$CONF_OPENVAS_WS_LOGIN = "admin";
$CONF_OPENVAS_WS_PASSWORD = "admin";
$CONF_OPENVAS_WS_ENDPOINT = "http://localhost:8080/webissues-server-1.1.4/client/security_tools/openvas/openvas.php";
$CONF_ID_ATTRIBUTE_FOLDER_WEB_URL = 366;
$CONF_ID_ATTRIBUTE_FOLDER_CODES_PATH = 365;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_USE = 364;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_IPSADDRESS = 363;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TOOL = 367;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TIME = 368;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_SEVERITY = 369;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TARGETID = 370;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TASKID = 371;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_REPORTID = 372;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_ALERTID = 373;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_TARGET = 360;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_CVE = 361;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_CWE = 362;
$CONF_ID_TYPE_FOLDER_BUGS = 2;
$CONF_ID_TYPE_FOLDER_SERVERS = 182;
$CONF_ID_TYPE_FOLDER_CODES = 183;
$CONF_ID_TYPE_FOLDER_WEB = 185;
$CONF_ID_TYPE_FOLDER_SCANS = 184;

?>